name: React CI/CD - Development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

permissions:
  contents: write
  pages: write
  id-token: write
  security-events: write

jobs:
  build:
    name: Build and Deploy React App
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cart

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Run Lint (optional)
        run: npm run lint || true

      - name: Run Tests (optional)
        run: npm test --if-present

      - name: Check if `useeffect.css` exists
        run: |
          echo "Checking if useeffect.css exists..."
          ls ./src/Component/State/useeffect.css || echo "useeffect.css not found"

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/development'
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          npm run deploy

  codeql-analysis:
    name: CodeQL Static Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
