name: React CI & Security Pipeline

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

permissions:
  contents: read
  security-events: write

jobs:
  react-quality-security:
    name: React Code Quality & Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier (Check Formatting)
        run: npm run format:check

      - name: Run ESLint (Linting)
        run: npm run lint

      - name: Run npm audit (Vulnerability Scan)
        run: npm audit --audit-level=moderate

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build React App
        run: npm run build

  codeql-analysis:
    name: CodeQL Static Analysis
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [javascript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
